### ISSUE TITLE
Add PurifyCSS?

### ISSUE THREAD

**Issue by HJThompson** [GoalSmashers/css-minification-benchmark#40]
It was posted in lots of places around a week ago and got pretty popular https://github.com/purifycss/purifycss

**Comment by XhmikosR** [comment]
That's not a minifier.

**Comment by HJThompson** [comment]
It does minify

**Comment by XhmikosR** [comment]
Sure it does, but its primary target isn't that.

**Comment by jakubpawlowicz** [comment]
It requires HTML / JS source which all minifiers covered here don't.
