### ISSUE TITLE
css-minification-benchmark not available on npmjs.com

### ISSUE THREAD

**Issue by marcinant** [GoalSmashers/css-minification-benchmark#43]
Hi,

`css-minification-benchmark` is not installable via: `npm install -g css-minification-benchmark`.

Could you describe installation procedure or upload this package to NPM?

**Comment by jakubpawlowicz** [comment]
Well I don't see a point in maintaining (and versioning!) it on npm when you can:

1. download a ZIP file
2. fetch the dependencies with `npm install`
