### ISSUE TITLE
update cssnano to 3.2.0

### ISSUE THREAD

**Issue by stevenvachon** [GoalSmashers/css-minification-benchmark#44]
Being built on postcss, I'm guessing that this library will get faster/better and would like to keep track of its performance progress.

**Comment by TrySound** [comment]
cssnano 3.3 released

**Comment by ben-eb** [comment]
This requires a rewrite of the benchmark to be async instead of sync. I've made provisions for that in https://github.com/ben-eb/css-minifiers v2, which the benchmark isn't currently using but would help reduce duplication.

**Comment by shinnn** [comment]
https://github.com/GoalSmashers/css-minification-benchmark/pull/45 has been merged.
