### ISSUE TITLE
Nuke unmaintained packages

### ISSUE THREAD

**Issue by XhmikosR** [GoalSmashers/css-minification-benchmark#59]
@jakubpawlowicz: how about dropping more-css?

**Comment by XhmikosR** [comment]
@jakubpawlowicz: I think we should also remove cssshrink, sqwish and ycssmin since they are not actively maintained.

**Comment by jakubpawlowicz** [comment]
How do we define "not actively maintained"?

**Comment by XhmikosR** [comment]
Well, my reasoning is simple:

1. cssshrink; last commit July 2014
2. more-css; doesn't work for any of our files so it's just extra noise
3. sqwish:  last commit July 2014
4. ycssmin: last commit October 2012
