### ISSUE TITLE
Link to results not showing results

### ISSUE THREAD

**Issue by Ariane-B** [GoalSmashers/css-minification-benchmark#89]
In the readme, there's a link that says:

> If you prefer to see results without cloning the repo [here are the most recent ones](https://goalsmashers.github.io/css-minification-benchmark/).

I suppose that link is supposed to show us the table that's in [index.html](https://github.com/GoalSmashers/css-minification-benchmark/blob/gh-pages/index.html). It just shows the same Readme, but without the files header.

**Comment by XhmikosR** [comment]
@jakubpawlowicz https://github.com/GoalSmashers/css-minification-benchmark/pull/84#issuecomment-613976929

**Comment by jakubpawlowicz** [comment]
It's fixed.
